services:
  - type: web
    name: monbackend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    build:
      pythonVersion: 3.11
